[package]
name = "northern_branch"
version = "0.1.0"
edition = "2024"

[lints.rust]
dead_code = "allow"

[lints.clippy]
all = { level = "warn", priority = -1 }
unwrap_used = "warn"
pedantic = "warn"
nursery = "warn"
